version: '3.8'

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=adminuser
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432
      
  app:
    depends_on:
      - postgresdb
    build: ./
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgresdb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
      - DB_PORT=5432
    stdin_open: true
    tty: true
    volumes:
      - ./src:/usr/src/app/src

volumes:
  db:
